export enum chatUpdateEnum {
     NEW_MESSAGE,
     DELETE_MESSAGE,
};

export const SET_CHAT = 'SET_CHAT';
export type SET_CHAT = typeof SET_CHAT;

export enum chatUpdateThunk {
     UPDATE_CHAT_API_STARTED = "UPDATE_CHAT_API_STARTED",
     UPDATE_CHAT_API_SUCESSS = 'UPDATE_CHAT_API_SUCESSS',
     UPDATE_CHAT_API_ERROR = 'UPDATE_CHAT_API_ERROR'
}

export enum chatFindThunk {
     FIND_CHAT_API_STARTED = 'FIND_CHAT_API_STARTED',
     FIND_CHAT_API_SUCESSS = 'FIND_CHAT_API_SUCESSS',
     FIND_CHAT_API_ERROR = 'FIND_CHAT_API_ERROR'
}

export enum chatDeleteThunk {
     DELETE_CHAT_API_STARTED = 'DELETE_CHAT_API_STARTED',
     DELETE_CHAT_API_SUCESSS = 'DELETE_CHAT_API_SUCESSS',
     DELETE_CHAT_API_ERROR = 'DELETE_CHAT_API_ERROR'
}
