export enum findChatsEnumThunk {

     FIND_CHATS_API_SUCESSS = 'FIND_CHATS_API_SUCESSS',
     FIND_CHATS_API_STARTED = 'FIND_CHATS_API_STARTED',
     FIND_CHATS_API_ERROR = 'FIND_CHATS_API_ERROR'

}

export const UPDATE_CHATS = 'UPDATE_CHATS';
export const DELETE_CHATS = 'DELETE_CHATS'