export enum chatUpdateEnum {
     NEW_MESSAGE,
     DELETE_MESSAGE,
};

export const UPDATE_CHAT = 'UPDATE_CHAT';
export type UPDATE_CHAT = typeof UPDATE_CHAT;

export const CHAT_RESET_STATE = 'CHAT_RESET_STATE';
export type CHAT_RESET_STATE = 'CHAT_RESET_STATE';


export const DELETE_CHAT = 'DELETE_CHAT';
export type DELETE_CHAT = typeof DELETE_CHAT;


export enum chatUpdateThunk {
     UPDATE_CHAT_API_STARTED = "UPDATE_CHAT_API_STARTED",
     UPDATE_CHAT_API_SUCESSS = 'UPDATE_CHAT_API_SUCESSS',
     UPDATE_CHAT_API_ERROR = 'UPDATE_CHAT_API_ERROR'
}

export enum chatFindThunk {
     FIND_CHAT_API_STARTED = 'FIND_CHAT_API_STARTED',
     FIND_CHAT_API_SUCESSS = 'FIND_CHAT_API_SUCESSS',
     FIND_CHAT_API_ERROR = 'FIND_CHAT_API_ERROR'
}

export enum chatDeleteThunk {
     DELETE_CHAT_API_STARTED = 'DELETE_CHAT_API_STARTED',
     DELETE_CHAT_API_SUCESSS = 'DELETE_CHAT_API_SUCESSS',
     DELETE_CHAT_API_ERROR = 'DELETE_CHAT_API_ERROR'
}

