



export enum searchUsersEnumThunk {

     SEARCH_USER_API_SUCESSS = 'SEARCH_USER_API_SUCESSS',
     SEARCH_USER_API_STARTED = 'SEARCH_USER_API_STARTED',
     SEARCH_USER_API_ERROR = 'SEARCH_USER_API_ERROR',
}


export enum searchUsersEnum {
     SET_USERS_SEARCH_MODE_ACTIVE_SYNC = 'SET_USERS_SEARCH_MODE_ACTIVE_SYNC',
     SET_INDEX_USER_SEARCHED_SELECTED = 'SET_INDEX_USER_SEARCHED_SELECTED'
}