
export enum findUserEnumThunk {

     FIND_USER_API_SUCCESS = 'FIND_USER_API_SUCCESS',
     FIND_USER_API_ERROR = 'FIND_USER_API_ERROR',
     FIND_USER_API_STARTED = 'FIND_USER_API_STARTED'
}

export enum updateUserEnumThunk {

     UPDATE_USER_API_SUCCESS = 'UPDATE_USER_API_SUCCESS',
     UPDATE_USER_API_ERROR = 'UPDATE_USER_API_ERROR',
     UPDATE_USER_API_STARTED = 'UPDATE_USER_API_STARTED'
}

export enum updateUserEnum {  

     SET_PASSWORD = 'SET_PASSWORD',
     SET_ACTIVE = 'SET_ACTIVE',
     SET_IMAGE_PROFILE = 'SET_IMAGE_PROFILE',
     ADD_CONTACT = 'ADD_CONTACT',
     DELETE_CONTACT = 'DELETE_CONTACT'
}
